name: Release ğŸ“¦

on:
    push:
      tags:
        - 'v*.*.*'
      paths-ignore:
        - 'README.md'
        - '.vscode'
        - '.idea'
    pull_request:
      branches:
        - master
        - main
      paths-ignore:
        - 'README.md'
        - '.vscode'
        - '.idea'

jobs:
  pyinstaller-build:
    name: Build and publish Python ğŸ distributions ğŸ“¦
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          python_ver: '3.10'
          spec: 'smtk.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'smtk'
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/smtk.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}